### ISSUE TITLE
FreeBSD No Translation File

### ISSUE THREAD

**Issue by javierpra** [metamorphose/metamorphose2#6]
Translation file is not being found on FBSD even after running messages/update_langs.sh.  The locale is set.  This does not affect Linux.

**Comment by ShadowKyogre** [comment]
@javierpra : It might be because [the if statement that manually installs the translations isn't considering FreeBSD too](https://github.com/metamorphose/metamorphose2/blob/master/Makefile#L75). I think It should be pretty easy to fix by simply adding an or statement to consider FreeBSD.

**Comment by javierpra** [comment]
Dropping support for FreeBSD.
