### ISSUE TITLE
PIL not found, but python2-pillow is installed

### ISSUE THREAD

**Issue by Soukyuu** [metamorphose/metamorphose2#9]
Running latest git snapshot on arch linux x64. As far as I know, PIL was replaced by pillow (and there is no PIL package in the repos or the AUR anymore), so I have installed python2-pillow from the official repositories:
```
community/python2-pillow 2.7.0-2 [installed]
    Python Imaging Library (PIL) fork. Python2 version.
```

Yet I'm still getting a `PIL not found` error message at startup. What could be wrong here?

**Comment by ShadowKyogre** [comment]
@Soukyuu: It's importing it from the wrong place.

https://github.com/metamorphose/metamorphose2/blob/b1f9e4d87492084af65e02ab8f4cf3f30313132f/src/picker/wxPickerView.py#L26

I'll go make a pull request so the developer(s) can fix this.
